[package]
name = "hello_rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
android_logger = "0.15.0"
fframes = { path = "../../fframes/fframes", features = ["mediacodec"] }
jni = "0.21"
log = "0.4.27"
